# Generated by Django 4.2.6 on 2024-01-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostModel',
            fields=[
                ('title', models.CharField(max_length=50)),
                ('memo', models.TextField()),
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
