# Generated by Django 4.2.6 on 2024-01-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_postmodel_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='memo',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='author',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='title',
            field=models.CharField(max_length=32),
        ),
    ]
