# Generated by Django 4.2.6 on 2024-01-26 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_remove_postmodel_memo_postmodel_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
