# Generated by Django 4.2.6 on 2024-01-31 01:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0010_alter_postmodel_published_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='postmodel',
            name='last_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='postmodel',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 31, 10, 45, 38, 744734), null=True),
        ),
    ]
