# Generated by Django 4.2.6 on 2024-02-01 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0013_alter_postmodel_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='published_date',
        ),
        migrations.AddField(
            model_name='postmodel',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 2, 1, 13, 28, 48, 101418), null=True),
        ),
    ]
